### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by sai-teja-ponugoti** [lazargugleta/findJob#1]
As the click event on summ in th code is opening the job description in a new tab, webdriver is unable to grab the job description part and is throwing an error.

error link :
https://i.imgur.com/PYBwXuF.png

tabs link : 
https://i.imgur.com/D4NaOrZ.png

As a result there s njs-desc class in indeed page which is causing the error.

Please advice on this.

**Comment by lazargugleta** [comment]
You did not find the link properly.
Try this link with my script: "https://www.indeed.com/jobs?q=data+engineer&l=United+States&start="

**Comment by sai-teja-ponugoti** [comment]
I used the same link. I did not change anything in your script. Can you run your script once and let me know. Indeed might have updated its pages. 

It seems your have done this recently. So we can rule out updated pages one. 

I ran the code using pychram pro in Ubuntu. Do I need to make any changes to web driver?

**Comment by lazargugleta** [comment]
Yes, it works perfectly, I just ran it again.
Did you install all the libraries as shown?

**Comment by lazargugleta** [comment]
Try running it like this in terminal:
python3.6 findJob.py
